import type { SQL } from 'drizzle-orm'
import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-sqlite'

type MigrationDB = MigrateUpArgs['db']

/*
  Adds the 4 new page globals from "bring all the pages into CMS" audit
  work (see src/globals/PrivacyPolicyPage.ts, TermsOfServicePage.ts,
  ThankYouPage.ts, SocialMediaManagementPage.ts): privacy-policy-page,
  terms-of-service-page, thank-you-page, social-media-management-page.
  (/contact/project deliberately excluded -- its IntakeFrame is a
  self-contained bundled app that must stay byte-identical, same
  precedent as the How-It-Works 3D scene staying code-only.)

  Hand-written rather than generated by `payload migrate:create` --
  that command hung indefinitely in this environment (no output, no
  error, growing memory) rather than the fast file-diff operation the
  README describes, so this follows the exact table/column/index
  conventions verified directly from the existing migrations instead
  (20260820_233310_add_drafts_versions_live_preview.ts's `final_cta` /
  `_final_cta_v` pair for a plain global, `footer_sitemap_column_links`
  / `_footer_v_version_sitemap_column_links` for an array field, and
  20260824_000000_add_trust_banner.ts for the overall hand-written
  pattern this file follows). Every new table is a from-scratch
  CREATE TABLE IF NOT EXISTS -- there is no existing data to rebuild,
  cascade-delete, or otherwise put at risk the way
  20260820_233310_add_drafts_versions_live_preview.ts's column-add
  rebuilds were (see that migration's own README section for the
  incident this avoids by construction).

  After creating each global's tables, `up()` calls `payload.updateGlobal`
  to populate real starting content (the exact copy migrated from each
  page's previously-hardcoded source, verbatim) as a PUBLISHED version --
  explicit `draft: false` throughout, since a version-enabled global's
  first row defaulting to `_status: 'draft'` is exactly the bug already
  documented in this project (every page's data fetch silently returning
  empty until someone manually republished).
*/

// This migration only ever CREATEs brand-new tables (no ALTER TABLE ADD
// COLUMN, unlike 20260824_000000_add_trust_banner.ts), so "duplicate
// column" is never a possible error mode here -- only "table already
// exists" (from a re-run, or the "cannot guarantee IF NOT EXISTS was
// enough" transient-failure scenario 20260820_233310's README section
// describes) needs handling.
function isTableExistsError(e: unknown): boolean {
  const err = e as { message?: unknown; cause?: { message?: unknown } } | null
  const msg = [e, err?.message, err?.cause, err?.cause?.message]
    .filter(Boolean)
    .map(String)
    .join(' | ')
  return msg.includes('already exists')
}

async function createTableIfNotExists(db: MigrationDB, ddl: SQL) {
  try {
    await db.run(ddl)
  } catch (e) {
    if (!isTableExistsError(e)) throw e
  }
}

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  // ---------------------------------------------------------------
  // privacy_policy_page
  // ---------------------------------------------------------------
  await createTableIfNotExists(db, sql`CREATE TABLE IF NOT EXISTS \`privacy_policy_page\` (
    \`id\` integer PRIMARY KEY NOT NULL,
    \`title\` text DEFAULT 'Privacy Policy' NOT NULL,
    \`dateline\` text DEFAULT 'Last updated · 6 August 2026' NOT NULL,
    \`body\` text NOT NULL,
    \`_status\` text DEFAULT 'draft',
    \`updated_at\` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
    \`created_at\` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL
  );
  `)
  await db.run(sql`CREATE INDEX IF NOT EXISTS \`privacy_policy_page__status_idx\` ON \`privacy_policy_page\` (\`_status\`);`)

  await createTableIfNotExists(db, sql`CREATE TABLE IF NOT EXISTS \`_privacy_policy_page_v\` (
    \`id\` integer PRIMARY KEY NOT NULL,
    \`version_title\` text DEFAULT 'Privacy Policy',
    \`version_dateline\` text DEFAULT 'Last updated · 6 August 2026',
    \`version_body\` text,
    \`version__status\` text DEFAULT 'draft',
    \`version_updated_at\` text,
    \`version_created_at\` text,
    \`created_at\` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
    \`updated_at\` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
    \`latest\` integer
  );
  `)
  await db.run(sql`CREATE INDEX IF NOT EXISTS \`_privacy_policy_page_v_version_version__status_idx\` ON \`_privacy_policy_page_v\` (\`version__status\`);`)
  await db.run(sql`CREATE INDEX IF NOT EXISTS \`_privacy_policy_page_v_created_at_idx\` ON \`_privacy_policy_page_v\` (\`created_at\`);`)
  await db.run(sql`CREATE INDEX IF NOT EXISTS \`_privacy_policy_page_v_updated_at_idx\` ON \`_privacy_policy_page_v\` (\`updated_at\`);`)
  await db.run(sql`CREATE INDEX IF NOT EXISTS \`_privacy_policy_page_v_latest_idx\` ON \`_privacy_policy_page_v\` (\`latest\`);`)

  // ---------------------------------------------------------------
  // terms_of_service_page
  // ---------------------------------------------------------------
  await createTableIfNotExists(db, sql`CREATE TABLE IF NOT EXISTS \`terms_of_service_page\` (
    \`id\` integer PRIMARY KEY NOT NULL,
    \`title\` text DEFAULT 'Terms of Service' NOT NULL,
    \`dateline\` text DEFAULT 'Last updated · 6 August 2026' NOT NULL,
    \`body\` text NOT NULL,
    \`_status\` text DEFAULT 'draft',
    \`updated_at\` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
    \`created_at\` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL
  );
  `)
  await db.run(sql`CREATE INDEX IF NOT EXISTS \`terms_of_service_page__status_idx\` ON \`terms_of_service_page\` (\`_status\`);`)

  await createTableIfNotExists(db, sql`CREATE TABLE IF NOT EXISTS \`_terms_of_service_page_v\` (
    \`id\` integer PRIMARY KEY NOT NULL,
    \`version_title\` text DEFAULT 'Terms of Service',
    \`version_dateline\` text DEFAULT 'Last updated · 6 August 2026',
    \`version_body\` text,
    \`version__status\` text DEFAULT 'draft',
    \`version_updated_at\` text,
    \`version_created_at\` text,
    \`created_at\` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
    \`updated_at\` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
    \`latest\` integer
  );
  `)
  await db.run(sql`CREATE INDEX IF NOT EXISTS \`_terms_of_service_page_v_version_version__status_idx\` ON \`_terms_of_service_page_v\` (\`version__status\`);`)
  await db.run(sql`CREATE INDEX IF NOT EXISTS \`_terms_of_service_page_v_created_at_idx\` ON \`_terms_of_service_page_v\` (\`created_at\`);`)
  await db.run(sql`CREATE INDEX IF NOT EXISTS \`_terms_of_service_page_v_updated_at_idx\` ON \`_terms_of_service_page_v\` (\`updated_at\`);`)
  await db.run(sql`CREATE INDEX IF NOT EXISTS \`_terms_of_service_page_v_latest_idx\` ON \`_terms_of_service_page_v\` (\`latest\`);`)

  // ---------------------------------------------------------------
  // thank_you_page (+ next_steps array)
  // ---------------------------------------------------------------
  await createTableIfNotExists(db, sql`CREATE TABLE IF NOT EXISTS \`thank_you_page\` (
    \`id\` integer PRIMARY KEY NOT NULL,
    \`hero_eyebrow\` text DEFAULT 'Submission Received',
    \`hero_title_line1\` text DEFAULT 'Got it —' NOT NULL,
    \`hero_title_line2\` text DEFAULT 'we''re on it.' NOT NULL,
    \`hero_subtitle\` text DEFAULT 'Thanks for reaching out to Slate Cinema. Your message is already in front of the team.',
    \`confirmed_label\` text DEFAULT 'Confirmed',
    \`primary_cta_label\` text DEFAULT 'View Our Work',
    \`primary_cta_href\` text DEFAULT '/portfolio',
    \`secondary_cta_label\` text DEFAULT 'Back to Home',
    \`secondary_cta_href\` text DEFAULT '/',
    \`_status\` text DEFAULT 'draft',
    \`updated_at\` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
    \`created_at\` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL
  );
  `)
  await db.run(sql`CREATE INDEX IF NOT EXISTS \`thank_you_page__status_idx\` ON \`thank_you_page\` (\`_status\`);`)

  await createTableIfNotExists(db, sql`CREATE TABLE IF NOT EXISTS \`thank_you_page_next_steps\` (
    \`_order\` integer NOT NULL,
    \`_parent_id\` integer NOT NULL,
    \`id\` text PRIMARY KEY NOT NULL,
    \`icon\` text NOT NULL,
    \`title\` text NOT NULL,
    \`body\` text NOT NULL,
    FOREIGN KEY (\`_parent_id\`) REFERENCES \`thank_you_page\`(\`id\`) ON UPDATE no action ON DELETE cascade
  );
  `)
  await db.run(sql`CREATE INDEX IF NOT EXISTS \`thank_you_page_next_steps_order_idx\` ON \`thank_you_page_next_steps\` (\`_order\`);`)
  await db.run(sql`CREATE INDEX IF NOT EXISTS \`thank_you_page_next_steps_parent_id_idx\` ON \`thank_you_page_next_steps\` (\`_parent_id\`);`)

  await createTableIfNotExists(db, sql`CREATE TABLE IF NOT EXISTS \`_thank_you_page_v\` (
    \`id\` integer PRIMARY KEY NOT NULL,
    \`version_hero_eyebrow\` text DEFAULT 'Submission Received',
    \`version_hero_title_line1\` text DEFAULT 'Got it —',
    \`version_hero_title_line2\` text DEFAULT 'we''re on it.',
    \`version_hero_subtitle\` text DEFAULT 'Thanks for reaching out to Slate Cinema. Your message is already in front of the team.',
    \`version_confirmed_label\` text DEFAULT 'Confirmed',
    \`version_primary_cta_label\` text DEFAULT 'View Our Work',
    \`version_primary_cta_href\` text DEFAULT '/portfolio',
    \`version_secondary_cta_label\` text DEFAULT 'Back to Home',
    \`version_secondary_cta_href\` text DEFAULT '/',
    \`version__status\` text DEFAULT 'draft',
    \`version_updated_at\` text,
    \`version_created_at\` text,
    \`created_at\` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
    \`updated_at\` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
    \`latest\` integer
  );
  `)
  await db.run(sql`CREATE INDEX IF NOT EXISTS \`_thank_you_page_v_version_version__status_idx\` ON \`_thank_you_page_v\` (\`version__status\`);`)
  await db.run(sql`CREATE INDEX IF NOT EXISTS \`_thank_you_page_v_created_at_idx\` ON \`_thank_you_page_v\` (\`created_at\`);`)
  await db.run(sql`CREATE INDEX IF NOT EXISTS \`_thank_you_page_v_updated_at_idx\` ON \`_thank_you_page_v\` (\`updated_at\`);`)
  await db.run(sql`CREATE INDEX IF NOT EXISTS \`_thank_you_page_v_latest_idx\` ON \`_thank_you_page_v\` (\`latest\`);`)

  await createTableIfNotExists(db, sql`CREATE TABLE IF NOT EXISTS \`_thank_you_page_v_version_next_steps\` (
    \`_order\` integer NOT NULL,
    \`_parent_id\` integer NOT NULL,
    \`id\` integer PRIMARY KEY NOT NULL,
    \`icon\` text,
    \`title\` text,
    \`body\` text,
    \`_uuid\` text,
    FOREIGN KEY (\`_parent_id\`) REFERENCES \`_thank_you_page_v\`(\`id\`) ON UPDATE no action ON DELETE cascade
  );
  `)
  await db.run(sql`CREATE INDEX IF NOT EXISTS \`_thank_you_page_v_version_next_steps_order_idx\` ON \`_thank_you_page_v_version_next_steps\` (\`_order\`);`)
  await db.run(sql`CREATE INDEX IF NOT EXISTS \`_thank_you_page_v_version_next_steps_parent_id_idx\` ON \`_thank_you_page_v_version_next_steps\` (\`_parent_id\`);`)

  // ---------------------------------------------------------------
  // social_media_management_page (+ how_it_works_steps, included_items arrays)
  // ---------------------------------------------------------------
  await createTableIfNotExists(db, sql`CREATE TABLE IF NOT EXISTS \`social_media_management_page\` (
    \`id\` integer PRIMARY KEY NOT NULL,
    \`hero_eyebrow\` text DEFAULT 'Distribution · Always On',
    \`hero_headline_text\` text DEFAULT 'We run social media for businesses that need to' NOT NULL,
    \`hero_headline_emphasis\` text DEFAULT 'focus on operations.' NOT NULL,
    \`hero_lede\` text NOT NULL,
    \`how_it_works_heading\` text DEFAULT 'How it works',
    \`included_heading\` text DEFAULT 'What''s included',
    \`cta_mono_tag\` text DEFAULT 'Now scheduling',
    \`cta_heading\` text DEFAULT 'One calendar. One approval. Action.',
    \`cta_body\` text DEFAULT 'Tell us about your business and what you want your social to do — we''ll get back to you with a plan.',
    \`cta_button_label\` text DEFAULT 'Schedule a call',
    \`cta_button_href\` text DEFAULT '/schedule-a-call',
    \`cta_alt_text\` text DEFAULT 'Or email',
    \`_status\` text DEFAULT 'draft',
    \`updated_at\` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
    \`created_at\` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL
  );
  `)
  await db.run(sql`CREATE INDEX IF NOT EXISTS \`social_media_management_page__status_idx\` ON \`social_media_management_page\` (\`_status\`);`)

  await createTableIfNotExists(db, sql`CREATE TABLE IF NOT EXISTS \`social_media_management_page_how_it_works_steps\` (
    \`_order\` integer NOT NULL,
    \`_parent_id\` integer NOT NULL,
    \`id\` text PRIMARY KEY NOT NULL,
    \`title\` text NOT NULL,
    \`body\` text NOT NULL,
    FOREIGN KEY (\`_parent_id\`) REFERENCES \`social_media_management_page\`(\`id\`) ON UPDATE no action ON DELETE cascade
  );
  `)
  await db.run(sql`CREATE INDEX IF NOT EXISTS \`smm_page_how_it_works_steps_order_idx\` ON \`social_media_management_page_how_it_works_steps\` (\`_order\`);`)
  await db.run(sql`CREATE INDEX IF NOT EXISTS \`smm_page_how_it_works_steps_parent_id_idx\` ON \`social_media_management_page_how_it_works_steps\` (\`_parent_id\`);`)

  await createTableIfNotExists(db, sql`CREATE TABLE IF NOT EXISTS \`social_media_management_page_included_items\` (
    \`_order\` integer NOT NULL,
    \`_parent_id\` integer NOT NULL,
    \`id\` text PRIMARY KEY NOT NULL,
    \`text\` text NOT NULL,
    FOREIGN KEY (\`_parent_id\`) REFERENCES \`social_media_management_page\`(\`id\`) ON UPDATE no action ON DELETE cascade
  );
  `)
  await db.run(sql`CREATE INDEX IF NOT EXISTS \`smm_page_included_items_order_idx\` ON \`social_media_management_page_included_items\` (\`_order\`);`)
  await db.run(sql`CREATE INDEX IF NOT EXISTS \`smm_page_included_items_parent_id_idx\` ON \`social_media_management_page_included_items\` (\`_parent_id\`);`)

  await createTableIfNotExists(db, sql`CREATE TABLE IF NOT EXISTS \`_social_media_management_page_v\` (
    \`id\` integer PRIMARY KEY NOT NULL,
    \`version_hero_eyebrow\` text DEFAULT 'Distribution · Always On',
    \`version_hero_headline_text\` text DEFAULT 'We run social media for businesses that need to',
    \`version_hero_headline_emphasis\` text DEFAULT 'focus on operations.',
    \`version_hero_lede\` text,
    \`version_how_it_works_heading\` text DEFAULT 'How it works',
    \`version_included_heading\` text DEFAULT 'What''s included',
    \`version_cta_mono_tag\` text DEFAULT 'Now scheduling',
    \`version_cta_heading\` text DEFAULT 'One calendar. One approval. Action.',
    \`version_cta_body\` text DEFAULT 'Tell us about your business and what you want your social to do — we''ll get back to you with a plan.',
    \`version_cta_button_label\` text DEFAULT 'Schedule a call',
    \`version_cta_button_href\` text DEFAULT '/schedule-a-call',
    \`version_cta_alt_text\` text DEFAULT 'Or email',
    \`version__status\` text DEFAULT 'draft',
    \`version_updated_at\` text,
    \`version_created_at\` text,
    \`created_at\` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
    \`updated_at\` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
    \`latest\` integer
  );
  `)
  await db.run(sql`CREATE INDEX IF NOT EXISTS \`_smm_page_v_version_version__status_idx\` ON \`_social_media_management_page_v\` (\`version__status\`);`)
  await db.run(sql`CREATE INDEX IF NOT EXISTS \`_smm_page_v_created_at_idx\` ON \`_social_media_management_page_v\` (\`created_at\`);`)
  await db.run(sql`CREATE INDEX IF NOT EXISTS \`_smm_page_v_updated_at_idx\` ON \`_social_media_management_page_v\` (\`updated_at\`);`)
  await db.run(sql`CREATE INDEX IF NOT EXISTS \`_smm_page_v_latest_idx\` ON \`_social_media_management_page_v\` (\`latest\`);`)

  await createTableIfNotExists(db, sql`CREATE TABLE IF NOT EXISTS \`_social_media_management_page_v_version_how_it_works_steps\` (
    \`_order\` integer NOT NULL,
    \`_parent_id\` integer NOT NULL,
    \`id\` integer PRIMARY KEY NOT NULL,
    \`title\` text,
    \`body\` text,
    \`_uuid\` text,
    FOREIGN KEY (\`_parent_id\`) REFERENCES \`_social_media_management_page_v\`(\`id\`) ON UPDATE no action ON DELETE cascade
  );
  `)
  await db.run(sql`CREATE INDEX IF NOT EXISTS \`_smm_page_v_ver_how_it_works_steps_order_idx\` ON \`_social_media_management_page_v_version_how_it_works_steps\` (\`_order\`);`)
  await db.run(sql`CREATE INDEX IF NOT EXISTS \`_smm_page_v_ver_how_it_works_steps_parent_id_idx\` ON \`_social_media_management_page_v_version_how_it_works_steps\` (\`_parent_id\`);`)

  await createTableIfNotExists(db, sql`CREATE TABLE IF NOT EXISTS \`_social_media_management_page_v_version_included_items\` (
    \`_order\` integer NOT NULL,
    \`_parent_id\` integer NOT NULL,
    \`id\` integer PRIMARY KEY NOT NULL,
    \`text\` text,
    \`_uuid\` text,
    FOREIGN KEY (\`_parent_id\`) REFERENCES \`_social_media_management_page_v\`(\`id\`) ON UPDATE no action ON DELETE cascade
  );
  `)
  await db.run(sql`CREATE INDEX IF NOT EXISTS \`_smm_page_v_ver_included_items_order_idx\` ON \`_social_media_management_page_v_version_included_items\` (\`_order\`);`)
  await db.run(sql`CREATE INDEX IF NOT EXISTS \`_smm_page_v_ver_included_items_parent_id_idx\` ON \`_social_media_management_page_v_version_included_items\` (\`_parent_id\`);`)

  // ---------------------------------------------------------------
  // Populate real starting content -- verbatim from each page's
  // previously-hardcoded source -- as PUBLISHED versions. Uses
  // Payload's own Local API (not raw INSERTs) so field validation,
  // richText JSON shape, and version-row creation all go through the
  // exact same path a real admin save would.
  // ---------------------------------------------------------------
  // Returns a plain object matching Lexical's SerializedEditorState shape
  // closely enough for Payload's richText field to accept and render it,
  // but not literally typed against that (large, version-specific,
  // partly-generic) type -- same tradeoff the seed script's own
  // `blocksToLexical` makes (src/seed/index.ts), just with link/bold
  // support added since these two legal documents actually need inline
  // formatting a plain block-of-paragraphs shape can't represent.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const richText = (paragraphs: Array<{ type: 'h2' | 'p'; children: Array<{ text: string; bold?: true; link?: string }> | string } | { type: 'ul'; items: string[] }>): any => {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const mk = (n: any) => ({ version: 1, direction: 'ltr' as const, format: '' as const, indent: 0, ...n })
    const textNode = (t: { text: string; bold?: true; link?: string }) => {
      const base = { type: 'text', text: t.text, version: 1, format: t.bold ? 1 : 0 }
      if (t.link) {
        return mk({
          type: 'link',
          fields: { url: t.link, newTab: false, linkType: 'custom' },
          children: [{ ...base, format: t.bold ? 1 : 0 }],
        })
      }
      return base
    }
    const children = paragraphs.map((p) => {
      if (p.type === 'ul') {
        return mk({
          type: 'list',
          tag: 'ul',
          listType: 'bullet',
          start: 1,
          children: p.items.map((item, i) =>
            mk({ type: 'listitem', value: i + 1, children: [{ type: 'text', text: item, version: 1 }] })
          ),
        })
      }
      const runs = typeof p.children === 'string' ? [{ text: p.children }] : p.children
      return mk({ type: p.type === 'h2' ? 'heading' : 'paragraph', tag: p.type === 'h2' ? 'h2' : undefined, children: runs.map(textNode) })
    })
    return { root: mk({ type: 'root', children }) }
  }

  await payload.updateGlobal({
    slug: 'privacy-policy-page',
    draft: false,
    data: {
      title: 'Privacy Policy',
      dateline: 'Last updated · 6 August 2026',
      body: richText([
        { type: 'p', children: 'Slate Cinema ("we", "us") provides social media management to client businesses. As part of that service we operate a publishing platform that a client uses to plan, review, approve and publish content to the client\'s own social media accounts. This policy explains what the platform collects, why, and how it is protected.' },
        { type: 'h2', children: 'Who this policy covers' },
        { type: 'p', children: 'It covers the businesses that use our social media management service, the people at those businesses who connect and approve accounts, and our own staff who operate the platform alongside them. Each client business connects its own accounts and remains the owner of those accounts.' },
        { type: 'h2', children: 'What we collect' },
        { type: 'ul', items: [
          'Connected account information. When an account owner authorizes the platform on a social network (Instagram, Facebook, TikTok, YouTube, X), we receive that account\'s identifier, username, profile picture and the access tokens the platform issues.',
          'Content submitted for publishing. Videos, images, captions and scheduling details, supplied either by the account owner or by our team on the account owner\'s instruction.',
          'Publishing and performance records. What was posted, when, who approved it, the resulting post link, and the performance statistics the platform reports back (views, reach, likes, comments, shares, saves).',
          'Operational records. The name of the person who created and approved each post, kept as an audit trail so every published post traces to a named approval.',
        ] },
        { type: 'p', children: 'We do not collect data about the followers or viewers of connected accounts beyond the aggregate statistics the platforms provide, and we do not buy, sell or rent personal information.' },
        { type: 'h2', children: 'How we use it' },
        { type: 'p', children: 'Solely to operate the service: to publish approved content to the accounts that authorized us, to show scheduling and performance information to the account owner and our team, and to keep records of who approved what. We do not use this data for advertising or profiling, and we do not share it with third parties other than the platform the content is being published to.' },
        { type: 'h2', children: 'Platform data' },
        { type: 'p', children: [
          { text: 'Access tokens and platform data are used only to perform the actions the account owner authorized. We follow the developer terms and policies of each platform, including the Instagram Platform Policy, the Facebook Platform Terms, the TikTok Developer Terms of Service, and the YouTube API Services Terms of Service. Use of YouTube API Services is also subject to the ' },
          { text: 'Google Privacy Policy', link: 'https://policies.google.com/privacy' },
          { text: '.' },
        ] },
        { type: 'p', children: 'We do not display, republish or syndicate TikTok content on this website or anywhere else. TikTok access is used only to publish content the account owner approved, to that owner\'s own account.' },
        { type: 'h2', children: 'Storage and security' },
        { type: 'p', children: 'Data is stored in a private database hosted by Supabase in the United States. Access tokens are held in an encrypted secrets vault, never in application code or ordinary database tables. Access is restricted to authorized Slate Cinema personnel and to the service processes that publish content. All transmission is encrypted over HTTPS/TLS.' },
        { type: 'h2', children: 'Disconnecting and revoking access' },
        { type: 'p', children: 'An account owner may disconnect a connected account at any time, in the platform\'s own Connected Accounts settings or by asking us. Disconnecting revokes our access token immediately and we stop publishing to that account. Revoking access from the social network\'s own settings has the same effect.' },
        { type: 'h2', children: 'Retention and deletion' },
        { type: 'p', children: [
          { text: 'Content and publishing records are retained while the account relationship is active and for up to 24 months afterwards for accounting and portfolio purposes. On request we delete the stored content, tokens and records for an account within 30 days, except where we are required to keep records by law. To request deletion, email ' },
          { text: 'info@slatecinema.com', link: 'mailto:info@slatecinema.com' },
          { text: ' with the account handle; we confirm in writing when it is done.' },
        ] },
        { type: 'h2', children: 'Your rights' },
        { type: 'p', children: 'Account owners may ask what we hold about their account, request a copy, request correction, or request deletion. Contact us using the details below and we will respond within 30 days.' },
        { type: 'h2', children: 'Children' },
        { type: 'p', children: 'The service is used by businesses and their representatives and is not directed to anyone under 18.' },
        { type: 'h2', children: 'Changes' },
        { type: 'p', children: 'If this policy changes materially we will update this page, change the date above, and notify connected account owners by email.' },
        { type: 'h2', children: 'Contact' },
        { type: 'p', children: [
          { text: 'Data controller: Slate Cinema Inc, 10800 Biscayne Blvd Ste 420, Miami, FL 33161, United States. Email: ' },
          { text: 'info@slatecinema.com', link: 'mailto:info@slatecinema.com' },
          { text: '. Web: ' },
          { text: 'slatecinema.com', link: 'https://slatecinema.com' },
          { text: '.' },
        ] },
      ]),
    },
    req,
  })

  await payload.updateGlobal({
    slug: 'terms-of-service-page',
    draft: false,
    data: {
      title: 'Terms of Service',
      dateline: 'Last updated · 6 August 2026',
      body: richText([
        { type: 'p', children: 'These terms govern use of the Slate Cinema social media management service and the publishing platform that supports it ("the Service"). The Service is provided by Slate Cinema Inc ("we", "us") to client businesses ("you") that engage us under a service agreement.' },
        { type: 'h2', children: 'What the Service does' },
        { type: 'p', children: 'The Service lets a client business plan social media content on a shared calendar, route it through an approval step, publish it to the client\'s own connected accounts on Instagram, Facebook, TikTok, YouTube and X, and see the performance of what was published. Each client business has its own workspace and its own connected accounts.' },
        { type: 'h2', children: 'Becoming a customer' },
        { type: 'p', children: [
          { text: 'Access is arranged through onboarding rather than instant self-serve signup. A business enquires, we agree scope and pricing, and the business then connects its own social accounts to its workspace. Enquiries: ' },
          { text: 'info@slatecinema.com', link: 'mailto:info@slatecinema.com' },
          { text: '.' },
        ] },
        { type: 'h2', children: 'Authorization' },
        { type: 'p', children: 'We publish only to accounts whose owner has explicitly connected them through the platform\'s own authorization flow. Connecting an account confirms that you own it or are authorized to act for its owner. Authorization can be withdrawn at any time from your platform settings or by asking us, and we stop publishing to that account immediately.' },
        { type: 'h2', children: 'Approval and responsibility for content' },
        { type: 'p', children: 'No content is published without an approval recorded against a named person. You are responsible for the accuracy and legality of content you supply or approve, and for the rights, licences and permissions needed for the media, music, footage and people appearing in it. We are responsible for publishing what was approved, to the account it was approved for, at the time it was scheduled.' },
        { type: 'h2', children: 'Acceptable use' },
        { type: 'p', children: 'The Service may not be used to publish content that is unlawful, infringing, deceptive, harassing, or that violates the rules of the destination platform. We may refuse or remove content that in our judgment breaches these terms or a platform\'s policies.' },
        { type: 'h2', children: 'Platform rules' },
        { type: 'p', children: 'Publishing through the Service is also subject to the terms of each destination platform, including Instagram, Facebook, TikTok, YouTube and X. Platform features, limits and availability are controlled by those platforms and may change without notice. We are not responsible for platform outages, rejections, rate limits, or changes to their APIs.' },
        { type: 'h2', children: 'Service availability' },
        { type: 'p', children: 'We aim to publish scheduled content on time but do not guarantee uninterrupted service. Scheduled posts may be delayed or fail due to platform errors, media processing problems, or connectivity issues. Where a post fails we record the error and notify the operator so it can be retried.' },
        { type: 'h2', children: 'Data' },
        { type: 'p', children: [
          { text: 'Our handling of content, tokens and statistics is described in our Privacy Policy at ' },
          { text: 'https://slatecinema.com/privacy-policy', link: 'https://slatecinema.com/privacy-policy' },
          { text: '.' },
        ] },
        { type: 'h2', children: 'Termination' },
        { type: 'p', children: 'Either party may end use of the Service at any time. On termination we stop publishing, and stored content, tokens and records are deleted on request as described in the Privacy Policy.' },
        { type: 'h2', children: 'Liability' },
        { type: 'p', children: 'The Service is provided on an "as is" basis to the extent permitted by law. Our liability arising from use of the Service is limited to the fees paid for the affected service in the three months preceding the claim. Nothing in these terms limits liability that cannot be limited by law.' },
        { type: 'h2', children: 'Changes' },
        { type: 'p', children: 'We may update these terms; the date above will change and connected account owners will be notified by email of material changes.' },
        { type: 'h2', children: 'Contact' },
        { type: 'p', children: [
          { text: 'Slate Cinema Inc, 10800 Biscayne Blvd Ste 420, Miami, FL 33161, United States. Email: ' },
          { text: 'info@slatecinema.com', link: 'mailto:info@slatecinema.com' },
          { text: '. Web: ' },
          { text: 'slatecinema.com', link: 'https://slatecinema.com' },
          { text: '.' },
        ] },
      ]),
    },
    req,
  })

  await payload.updateGlobal({
    slug: 'thank-you-page',
    draft: false,
    data: {
      hero: {
        eyebrow: 'Submission Received',
        titleLine1: 'Got it —',
        titleLine2: "we're on it.",
        subtitle: 'Thanks for reaching out to Slate Cinema. Your message is already in front of the team.',
      },
      confirmedLabel: 'Confirmed',
      nextSteps: [
        { icon: 'Mail', title: 'Check your inbox', body: 'A confirmation just landed — reply to it any time if you think of something to add.' },
        { icon: 'Clock3', title: 'Replies within minutes', body: 'A real producer reviews every submission personally — no queue, no bot.' },
        { icon: 'PlayCircle', title: 'See more of our work', body: 'While you wait, take a look at recent projects across every industry we shoot.' },
      ],
      primaryCtaLabel: 'View Our Work',
      primaryCtaHref: '/portfolio',
      secondaryCtaLabel: 'Back to Home',
      secondaryCtaHref: '/',
    },
    req,
  })

  await payload.updateGlobal({
    slug: 'social-media-management-page',
    draft: false,
    data: {
      hero: {
        eyebrow: 'Distribution · Always On',
        headlineText: 'We run social media for businesses that need to',
        headlineEmphasis: 'focus on operations.',
        lede: richText([
          { type: 'p', children: [
            { text: 'Slate Cinema plans, produces, schedules and publishes social content for client businesses across Instagram, Facebook, TikTok, YouTube and X — from one calendar, with one approval step, ' },
            { text: "on the client's own accounts", bold: true },
            { text: '. The same crew that shoots your story keeps it on screen, week after week.' },
          ] },
        ]),
      },
      howItWorks: {
        heading: 'How it works',
        steps: [
          { title: 'Your workspace', body: richText([{ type: 'p', children: "Every client business gets its own workspace: its own calendar, its own content library, its own approvals." }]) },
          { title: 'Your accounts stay yours', body: richText([{ type: 'p', children: [
            { text: "You connect your own social accounts through each platform's official authorization screen. " },
            { text: 'You own the accounts, the audience and the content.', bold: true },
            { text: ' You can disconnect at any time, and access ends immediately.' },
          ] }]) },
          { title: 'We build the calendar', body: richText([{ type: 'p', children: 'We plan the month, produce or edit the content, write the captions, and load everything into your calendar with the dates and times we recommend.' }]) },
          { title: 'You approve — final cut is yours', body: richText([{ type: 'p', children: [
            { text: 'Nothing publishes until someone at your business approves it. Every published post traces back to a named approval.' },
          ] }]) },
          { title: 'It publishes, and you see what happened', body: richText([{ type: 'p', children: 'Approved posts go out automatically at the scheduled time, to every platform you selected. Views, reach, engagement and follower growth come back into the same dashboard.' }]) },
        ],
      },
      included: {
        heading: "What's included",
        items: [
          { text: 'Content calendar across Instagram, Facebook, TikTok, YouTube and X' },
          { text: 'Post production and editing, or scheduling of content you supply' },
          { text: 'Captions, hashtags and posting-time strategy' },
          { text: 'An approval gate before anything goes live' },
          { text: 'Performance reporting in one place, updated automatically' },
        ],
      },
      cta: {
        monoTag: 'Now scheduling',
        heading: 'One calendar. One approval. Action.',
        body: "Tell us about your business and what you want your social to do — we'll get back to you with a plan.",
        buttonLabel: 'Schedule a call',
        buttonHref: '/schedule-a-call',
        altText: 'Or email',
      },
    },
    req,
  })
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  const tables = [
    '_social_media_management_page_v_version_included_items',
    '_social_media_management_page_v_version_how_it_works_steps',
    '_social_media_management_page_v',
    'social_media_management_page_included_items',
    'social_media_management_page_how_it_works_steps',
    'social_media_management_page',
    '_thank_you_page_v_version_next_steps',
    '_thank_you_page_v',
    'thank_you_page_next_steps',
    'thank_you_page',
    '_terms_of_service_page_v',
    'terms_of_service_page',
    '_privacy_policy_page_v',
    'privacy_policy_page',
  ]
  for (const table of tables) {
    await db.run(sql.raw(`DROP TABLE IF EXISTS \`${table}\`;`))
  }
}
