import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-sqlite'

/*
  Adds the Media.prefix column the @payloadcms/storage-s3 plugin needs
  (see payload.config.ts's s3Storage collections.media.prefix: 'slate').
  Generated by `migrate:create` alongside an unrelated, cosmetic diff on
  home_page (SQL-level DEFAULT changes for trustSection.eyebrow's wording
  and results.*Target's numbers, both already-live via the Payload field
  config's own defaultValue -- Payload resolves defaultValue in JS before
  building inserts, it never reads the SQL column's DEFAULT clause, so
  that diff has zero functional effect either way). Hand-trimmed down to
  just the one real, needed change so this migration ships tightly
  scoped, especially given the drafts/versions migration's track record
  this session -- see src/migrations/README.md.
*/
export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  // Same defensive pattern as the drafts/versions migration's ADD COLUMN
  // statements (see README) -- SQLite has no ADD COLUMN IF NOT EXISTS, so
  // swallow "duplicate column name" specifically rather than assume this
  // never gets re-run against a DB that already has it.
  try {
    await db.run(sql`ALTER TABLE \`media\` ADD \`prefix\` text DEFAULT 'slate';`)
  } catch (e) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const err = e as any
    const msg = [err, err && err.message, err && err.cause, err && err.cause && err.cause.message, err && err.cause && err.cause.cause, err && err.cause && err.cause.cause && err.cause.cause.message]
      .filter(Boolean).map(String).join(' | ')
    if (!msg.includes('duplicate column name')) throw e
  }
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.run(sql`ALTER TABLE \`media\` DROP COLUMN \`prefix\`;`)
}
