/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    industries: Industry;
    'portfolio-projects': PortfolioProject;
    'journal-posts': JournalPost;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    industries: IndustriesSelect<false> | IndustriesSelect<true>;
    'portfolio-projects': PortfolioProjectsSelect<false> | PortfolioProjectsSelect<true>;
    'journal-posts': JournalPostsSelect<false> | JournalPostsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    navigation: Navigation;
    footer: Footer;
    'site-settings': SiteSetting;
    pipeline: Pipeline;
    'final-cta': FinalCta;
    'ready-to-talk': ReadyToTalk;
    'home-page': HomePage;
    'how-it-works-page': HowItWorksPage;
    'portfolio-index-page': PortfolioIndexPage;
    'contact-page': ContactPage;
    'schedule-a-call-page': ScheduleACallPage;
  };
  globalsSelect: {
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    pipeline: PipelineSelect<false> | PipelineSelect<true>;
    'final-cta': FinalCtaSelect<false> | FinalCtaSelect<true>;
    'ready-to-talk': ReadyToTalkSelect<false> | ReadyToTalkSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'how-it-works-page': HowItWorksPageSelect<false> | HowItWorksPageSelect<true>;
    'portfolio-index-page': PortfolioIndexPageSelect<false> | PortfolioIndexPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'schedule-a-call-page': ScheduleACallPageSelect<false> | ScheduleACallPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    username: string;
  };
  login: {
    password: string;
    username: string;
  };
  registerFirstUser: {
    password: string;
    username: string;
  };
  unlock: {
    username: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  roles?: ('admin' | 'editor')[] | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email?: string | null;
  username: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries".
 */
export interface Industry {
  id: number;
  slug: string;
  label: string;
  icon:
    | 'Film'
    | 'Dumbbell'
    | 'Plane'
    | 'Building2'
    | 'HeartPulse'
    | 'ShoppingBag'
    | 'Briefcase'
    | 'Users'
    | 'GraduationCap';
  /**
   * Hex color, e.g. #00AEEF
   */
  accent: string;
  /**
   * Short one-liner used by the industry wheel
   */
  blurb: string;
  /**
   * Longer paragraph used on the individual industry page
   */
  description: string;
  stat: string;
  heroImage?: (number | null) | Media;
  heroVideo?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  stats?:
    | {
        value: number;
        suffix?: string | null;
        label: string;
        id?: string | null;
      }[]
    | null;
  services?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional — real client quote only, leave blank if none
   */
  testimonial?: {
    quote?: string | null;
    name?: string | null;
    role?: string | null;
    company?: string | null;
  };
  /**
   * Optional — rich bento cards for the individual industry page
   */
  serviceCards?:
    | {
        title: string;
        description: string;
        /**
         * e.g. "+212% PDP conversion"
         */
        outcome: string;
        deliverables?:
          | {
              item: string;
              id?: string | null;
            }[]
          | null;
        /**
         * e.g. "60–120s · 4–6 wks"
         */
        meta?: string | null;
        image?: (number | null) | Media;
        video?: (number | null) | Media;
        featured?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional — video testimonial + case-study proof cards
   */
  videoTestimonials?:
    | {
        quote: string;
        name: string;
        role: string;
        company: string;
        video: number | Media;
        outcome: string;
        poster?: (number | null) | Media;
        logo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional — process timeline
   */
  process?:
    | {
        week: string;
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional — FAQ accordion
   */
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-projects".
 */
export interface PortfolioProject {
  id: number;
  title: string;
  category: string;
  company: string;
  /**
   * Poster image (stands in wherever video can't render)
   */
  poster: number | Media;
  copy: string;
  /**
   * Featured cut shown in the project card modal
   */
  video?: (number | null) | Media;
  /**
   * Paste a Vimeo URL or ID -- takes priority over the uploaded file when set
   */
  videoVimeoUrl?: string | null;
  metrics?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Lower numbers show first
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-posts".
 */
export interface JournalPost {
  id: number;
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  /**
   * Hex color, e.g. #00AEEF
   */
  accent: string;
  /**
   * Display string, e.g. "July 2026"
   */
  date: string;
  /**
   * e.g. "6 min read"
   */
  readTime: string;
  coverImage: number | Media;
  author: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'industries';
        value: number | Industry;
      } | null)
    | ({
        relationTo: 'portfolio-projects';
        value: number | PortfolioProject;
      } | null)
    | ({
        relationTo: 'journal-posts';
        value: number | JournalPost;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  username?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries_select".
 */
export interface IndustriesSelect<T extends boolean = true> {
  slug?: T;
  label?: T;
  icon?: T;
  accent?: T;
  blurb?: T;
  description?: T;
  stat?: T;
  heroImage?: T;
  heroVideo?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        suffix?: T;
        label?: T;
        id?: T;
      };
  services?:
    | T
    | {
        name?: T;
        id?: T;
      };
  testimonial?:
    | T
    | {
        quote?: T;
        name?: T;
        role?: T;
        company?: T;
      };
  serviceCards?:
    | T
    | {
        title?: T;
        description?: T;
        outcome?: T;
        deliverables?:
          | T
          | {
              item?: T;
              id?: T;
            };
        meta?: T;
        image?: T;
        video?: T;
        featured?: T;
        id?: T;
      };
  videoTestimonials?:
    | T
    | {
        quote?: T;
        name?: T;
        role?: T;
        company?: T;
        video?: T;
        outcome?: T;
        poster?: T;
        logo?: T;
        id?: T;
      };
  process?:
    | T
    | {
        week?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-projects_select".
 */
export interface PortfolioProjectsSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  company?: T;
  poster?: T;
  copy?: T;
  video?: T;
  videoVimeoUrl?: T;
  metrics?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-posts_select".
 */
export interface JournalPostsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  excerpt?: T;
  category?: T;
  accent?: T;
  date?: T;
  readTime?: T;
  coverImage?: T;
  author?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Rendered after Home and the Portfolio dropdown, in order
   */
  links?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  ctaButton: {
    label: string;
    href: string;
  };
  /**
   * Where the "Client Portal" nav link sends visitors.
   */
  clientPortalHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  marqueeItems?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  cta: {
    heading: string;
    buttonLabel: string;
    buttonHref: string;
  };
  newsletter: {
    heading: string;
    sentence: string;
    placeholder?: string | null;
    buttonLabel?: string | null;
  };
  sitemapColumn?: {
    heading?: string | null;
    links?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
  };
  bottomBar?: {
    craftedWithLoveText?: string | null;
    privacyHref?: string | null;
    termsHref?: string | null;
    clientPortalHref?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  seo?: {
    titleTemplate?: string | null;
    /**
     * TikTok Content Posting API requirement: the homepage tab title must be literally "Slate Cinema" -- no tagline, no template suffix.
     */
    defaultTitle?: string | null;
    defaultDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  contact: {
    email: string;
    phone: string;
    studioName?: string | null;
    addressLine?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    hours?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pipeline".
 */
export interface Pipeline {
  id: number;
  /**
   * Section header shown above the pipeline on both Home and How It Works
   */
  heading?: {
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
  };
  categories?:
    | {
        /**
         * e.g. "pre-production" -- used as the React key, keep stable
         */
        categoryId: string;
        title: string;
        video: number | Media;
        /**
         * Hex color
         */
        color: string;
        services?:
          | {
              name: string;
              /**
               * Shown on How It Works detail panel
               */
              desc?: string | null;
              /**
               * Shown on Pre-Production beat overlay tags instead of a description
               */
              tags?:
                | {
                    tag: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "final-cta".
 */
export interface FinalCta {
  id: number;
  eyebrow?: string | null;
  headlineLine1: string;
  headlineLine2: string;
  description: string;
  buttonLabel: string;
  buttonHref: string;
  trustNote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ready-to-talk".
 */
export interface ReadyToTalk {
  id: number;
  eyebrow?: string | null;
  headline: string;
  description: string;
  badges?:
    | {
        icon: 'Clock3' | 'Users' | 'ShieldCheck' | 'Target' | 'Wallet' | 'Sparkles' | 'CalendarClock';
        label: string;
        id?: string | null;
      }[]
    | null;
  prepItems?:
    | {
        icon: 'Clock3' | 'Users' | 'ShieldCheck' | 'Target' | 'Wallet' | 'Sparkles' | 'CalendarClock';
        label: string;
        desc: string;
        id?: string | null;
      }[]
    | null;
  buttonLabel?: string | null;
  buttonHref?: string | null;
  note?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero: {
    wordmarkPart1: string;
    wordmarkPart2: string;
    subtitle: string;
    ctaLabel: string;
    ctaHref: string;
    secondaryCtaLabel?: string | null;
    secondaryCtaHref?: string | null;
  };
  /**
   * The scattered-then-assembled 3D text moment between Pipeline and Results
   */
  mediaVoid?: {
    lines?:
      | {
          text: string;
          /**
           * Hex color
           */
          color: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * The 3-phase pinned scroll section ("WE ENGINEER ATTENTION" / "EVERY FRAME" / "DOMINATE YOUR MARKET")
   */
  industryStandards?: {
    phase1?: {
      eyebrow?: string | null;
      headlineLine1?: string | null;
      headlineLine2?: string | null;
      description?: string | null;
    };
    phase2?: {
      eyebrow?: string | null;
      headline?: string | null;
      /**
       * Words that morph/cycle in place under the headline
       */
      morphWords?:
        | {
            word: string;
            id?: string | null;
          }[]
        | null;
      description?: string | null;
    };
    phase3?: {
      eyebrow?: string | null;
      headline?: string | null;
      description?: string | null;
      ctaLabel?: string | null;
      ctaHref?: string | null;
    };
  };
  trustSection: {
    eyebrow: string;
    ratingText?: string | null;
    marqueeLabel?: string | null;
    /**
     * The 3 large partner marks (Meta, Alo, B&H)
     */
    flagshipLogos?:
      | {
          name: string;
          logo: number | Media;
          id?: string | null;
        }[]
      | null;
    /**
     * The scrolling client-logo marquee below the flagship marks
     */
    marqueeClients?:
      | {
          name: string;
          logo: number | Media;
          id?: string | null;
        }[]
      | null;
  };
  results: {
    viewsTarget?: number | null;
    likesTarget?: number | null;
    commentsTarget?: number | null;
    reachPercent?: string | null;
    description: string;
    ctaLabel?: string | null;
    ctaHref?: string | null;
  };
  reviews?: {
    eyebrow?: string | null;
    headlineLine1?: string | null;
    headlineLine2?: string | null;
    ratingText?: string | null;
    videoTestimonialsLabel?: string | null;
    googleReviewsLabel?: string | null;
    /**
     * Curated Google reviews -- kept to exactly 3 per the client's own instruction
     */
    testimonials?:
      | {
          quote: string;
          name: string;
          role: string;
          company: string;
          rating?: number | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "how-it-works-page".
 */
export interface HowItWorksPage {
  id: number;
  /**
   * StoryboardHero text overlay -- the 3D scene/choreography itself stays code
   */
  hero?: {
    eyebrow?: string | null;
    title?: string | null;
    subtitle?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
  };
  processOverview?: {
    eyebrow?: string | null;
    headline?: string | null;
    /**
     * The connector-line summary strip -- should mirror Pipeline's 4 categories
     */
    timelineSteps?:
      | {
          title: string;
          color: string;
          line: string;
          id?: string | null;
        }[]
      | null;
  };
  behindTheScenes?: {
    eyebrow?: string | null;
    headline?: string | null;
    subhead?: string | null;
    stills?:
      | {
          image: number | Media;
          label: string;
          desc: string;
          span?: ('normal' | 'wide' | 'tall') | null;
          id?: string | null;
        }[]
      | null;
  };
  processWalkthrough?: {
    eyebrow?: string | null;
    headline?: string | null;
    subhead?: string | null;
    /**
     * Should mirror Pipeline's 4 categories
     */
    phases?:
      | {
          title: string;
          color: string;
          video: number | Media;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * The 4 animated counters (1hr / 3wk / 90% / 50+)
   */
  statsBand?:
    | {
        value: number;
        suffix?: string | null;
        label: string;
        id?: string | null;
      }[]
    | null;
  guarantees?:
    | {
        icon: 'Clock' | 'ShieldCheck' | 'RefreshCw' | 'Handshake';
        title: string;
        desc: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-index-page".
 */
export interface PortfolioIndexPage {
  id: number;
  hero?: {
    video?: (number | null) | Media;
    title?: string | null;
    date?: string | null;
    scrollToExpandLabel?: string | null;
    description?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
  };
  reelCarousel?: {
    eyebrow?: string | null;
    headline?: string | null;
    subhead?: string | null;
  };
  industriesSection?: {
    eyebrow?: string | null;
    headline?: string | null;
  };
  /**
   * Unused -- filter chips were removed from the portfolio grid per client request.
   */
  portfolioFilters?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  hero?: {
    eyebrow?: string | null;
    titleLine1?: string | null;
    titleLine2?: string | null;
    subtitle?: string | null;
  };
  whatHappensNext?: {
    eyebrow?: string | null;
    headline?: string | null;
    subhead?: string | null;
    formPrompt?: string | null;
    badges?:
      | {
          icon:
            | 'FileText'
            | 'PhoneCall'
            | 'FileCheck2'
            | 'Clapperboard'
            | 'Receipt'
            | 'Repeat'
            | 'BadgeCheck'
            | 'HelpCircle'
            | 'ClipboardList'
            | 'CalendarClock'
            | 'Timer'
            | 'ShieldCheck'
            | 'Mail'
            | 'Clock3'
            | 'Users'
            | 'Wallet'
            | 'Target'
            | 'Sparkles'
            | 'MessageCircleMore'
            | 'Phone'
            | 'MapPin';
          label: string;
          id?: string | null;
        }[]
      | null;
    steps?:
      | {
          icon:
            | 'FileText'
            | 'PhoneCall'
            | 'FileCheck2'
            | 'Clapperboard'
            | 'Receipt'
            | 'Repeat'
            | 'BadgeCheck'
            | 'HelpCircle'
            | 'ClipboardList'
            | 'CalendarClock'
            | 'Timer'
            | 'ShieldCheck'
            | 'Mail'
            | 'Clock3'
            | 'Users'
            | 'Wallet'
            | 'Target'
            | 'Sparkles'
            | 'MessageCircleMore'
            | 'Phone'
            | 'MapPin';
          step: string;
          title: string;
          desc: string;
          id?: string | null;
        }[]
      | null;
  };
  stageRouter?: {
    eyebrow?: string | null;
    headline?: string | null;
    subhead?: string | null;
    stages?:
      | {
          icon:
            | 'FileText'
            | 'PhoneCall'
            | 'FileCheck2'
            | 'Clapperboard'
            | 'Receipt'
            | 'Repeat'
            | 'BadgeCheck'
            | 'HelpCircle'
            | 'ClipboardList'
            | 'CalendarClock'
            | 'Timer'
            | 'ShieldCheck'
            | 'Mail'
            | 'Clock3'
            | 'Users'
            | 'Wallet'
            | 'Target'
            | 'Sparkles'
            | 'MessageCircleMore'
            | 'Phone'
            | 'MapPin';
          step: string;
          title: string;
          desc: string;
          ctaLabel: string;
          href: string;
          accent: string;
          id?: string | null;
        }[]
      | null;
  };
  leadForm?: {
    eyebrow?: string | null;
    headline?: string | null;
    description?: string | null;
    badges?:
      | {
          icon:
            | 'FileText'
            | 'PhoneCall'
            | 'FileCheck2'
            | 'Clapperboard'
            | 'Receipt'
            | 'Repeat'
            | 'BadgeCheck'
            | 'HelpCircle'
            | 'ClipboardList'
            | 'CalendarClock'
            | 'Timer'
            | 'ShieldCheck'
            | 'Mail'
            | 'Clock3'
            | 'Users'
            | 'Wallet'
            | 'Target'
            | 'Sparkles'
            | 'MessageCircleMore'
            | 'Phone'
            | 'MapPin';
          label: string;
          id?: string | null;
        }[]
      | null;
    submitLabel?: string | null;
    successMessage?: string | null;
  };
  contactMethods?: {
    eyebrow?: string | null;
    headline?: string | null;
    description?: string | null;
    /**
     * "Handled With Care" per client feedback (was "No Bots, Ever")
     */
    badges?:
      | {
          icon:
            | 'FileText'
            | 'PhoneCall'
            | 'FileCheck2'
            | 'Clapperboard'
            | 'Receipt'
            | 'Repeat'
            | 'BadgeCheck'
            | 'HelpCircle'
            | 'ClipboardList'
            | 'CalendarClock'
            | 'Timer'
            | 'ShieldCheck'
            | 'Mail'
            | 'Clock3'
            | 'Users'
            | 'Wallet'
            | 'Target'
            | 'Sparkles'
            | 'MessageCircleMore'
            | 'Phone'
            | 'MapPin';
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Address/hours/email pull from Site Settings > Contact -- this only covers section copy
   */
  studioLocation?: {
    eyebrow?: string | null;
    headlineLine1?: string | null;
    headlineLine2?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule-a-call-page".
 */
export interface ScheduleACallPage {
  id: number;
  hero?: {
    eyebrow?: string | null;
    titleLine1?: string | null;
    titleLine2?: string | null;
    subtitle?: string | null;
  };
  /**
   * Section header shown above the GHL booking widget on /schedule-a-call. Only eyebrow/sessionLabel/durationLabel/headline are used since 2026-08-20 -- the widget itself (real availability, real appointments) replaced the old static date/time grid, so the rest of these fields describe UI that no longer exists. Left in place rather than removed since deleting fields needs a real migration; just harmless unused data now.
   */
  calendar?: {
    eyebrow?: string | null;
    headline?: string | null;
    sessionLabel?: string | null;
    durationLabel?: string | null;
    monthLabel?: string | null;
    selectDateLabel?: string | null;
    selectTimeLabel?: string | null;
    confirmLabel?: string | null;
    confirmedLabel?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  links?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  ctaButton?:
    | T
    | {
        label?: T;
        href?: T;
      };
  clientPortalHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  marqueeItems?:
    | T
    | {
        text?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        heading?: T;
        buttonLabel?: T;
        buttonHref?: T;
      };
  newsletter?:
    | T
    | {
        heading?: T;
        sentence?: T;
        placeholder?: T;
        buttonLabel?: T;
      };
  sitemapColumn?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
      };
  bottomBar?:
    | T
    | {
        craftedWithLoveText?: T;
        privacyHref?: T;
        termsHref?: T;
        clientPortalHref?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        titleTemplate?: T;
        defaultTitle?: T;
        defaultDescription?: T;
        ogImage?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        studioName?: T;
        addressLine?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        hours?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pipeline_select".
 */
export interface PipelineSelect<T extends boolean = true> {
  heading?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  categories?:
    | T
    | {
        categoryId?: T;
        title?: T;
        video?: T;
        color?: T;
        services?:
          | T
          | {
              name?: T;
              desc?: T;
              tags?:
                | T
                | {
                    tag?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "final-cta_select".
 */
export interface FinalCtaSelect<T extends boolean = true> {
  eyebrow?: T;
  headlineLine1?: T;
  headlineLine2?: T;
  description?: T;
  buttonLabel?: T;
  buttonHref?: T;
  trustNote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ready-to-talk_select".
 */
export interface ReadyToTalkSelect<T extends boolean = true> {
  eyebrow?: T;
  headline?: T;
  description?: T;
  badges?:
    | T
    | {
        icon?: T;
        label?: T;
        id?: T;
      };
  prepItems?:
    | T
    | {
        icon?: T;
        label?: T;
        desc?: T;
        id?: T;
      };
  buttonLabel?: T;
  buttonHref?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        wordmarkPart1?: T;
        wordmarkPart2?: T;
        subtitle?: T;
        ctaLabel?: T;
        ctaHref?: T;
        secondaryCtaLabel?: T;
        secondaryCtaHref?: T;
      };
  mediaVoid?:
    | T
    | {
        lines?:
          | T
          | {
              text?: T;
              color?: T;
              id?: T;
            };
      };
  industryStandards?:
    | T
    | {
        phase1?:
          | T
          | {
              eyebrow?: T;
              headlineLine1?: T;
              headlineLine2?: T;
              description?: T;
            };
        phase2?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              morphWords?:
                | T
                | {
                    word?: T;
                    id?: T;
                  };
              description?: T;
            };
        phase3?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              description?: T;
              ctaLabel?: T;
              ctaHref?: T;
            };
      };
  trustSection?:
    | T
    | {
        eyebrow?: T;
        ratingText?: T;
        marqueeLabel?: T;
        flagshipLogos?:
          | T
          | {
              name?: T;
              logo?: T;
              id?: T;
            };
        marqueeClients?:
          | T
          | {
              name?: T;
              logo?: T;
              id?: T;
            };
      };
  results?:
    | T
    | {
        viewsTarget?: T;
        likesTarget?: T;
        commentsTarget?: T;
        reachPercent?: T;
        description?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  reviews?:
    | T
    | {
        eyebrow?: T;
        headlineLine1?: T;
        headlineLine2?: T;
        ratingText?: T;
        videoTestimonialsLabel?: T;
        googleReviewsLabel?: T;
        testimonials?:
          | T
          | {
              quote?: T;
              name?: T;
              role?: T;
              company?: T;
              rating?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "how-it-works-page_select".
 */
export interface HowItWorksPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  processOverview?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        timelineSteps?:
          | T
          | {
              title?: T;
              color?: T;
              line?: T;
              id?: T;
            };
      };
  behindTheScenes?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        subhead?: T;
        stills?:
          | T
          | {
              image?: T;
              label?: T;
              desc?: T;
              span?: T;
              id?: T;
            };
      };
  processWalkthrough?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        subhead?: T;
        phases?:
          | T
          | {
              title?: T;
              color?: T;
              video?: T;
              description?: T;
              id?: T;
            };
      };
  statsBand?:
    | T
    | {
        value?: T;
        suffix?: T;
        label?: T;
        id?: T;
      };
  guarantees?:
    | T
    | {
        icon?: T;
        title?: T;
        desc?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-index-page_select".
 */
export interface PortfolioIndexPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        video?: T;
        title?: T;
        date?: T;
        scrollToExpandLabel?: T;
        description?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  reelCarousel?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        subhead?: T;
      };
  industriesSection?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
      };
  portfolioFilters?:
    | T
    | {
        name?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        titleLine1?: T;
        titleLine2?: T;
        subtitle?: T;
      };
  whatHappensNext?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        subhead?: T;
        formPrompt?: T;
        badges?:
          | T
          | {
              icon?: T;
              label?: T;
              id?: T;
            };
        steps?:
          | T
          | {
              icon?: T;
              step?: T;
              title?: T;
              desc?: T;
              id?: T;
            };
      };
  stageRouter?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        subhead?: T;
        stages?:
          | T
          | {
              icon?: T;
              step?: T;
              title?: T;
              desc?: T;
              ctaLabel?: T;
              href?: T;
              accent?: T;
              id?: T;
            };
      };
  leadForm?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        description?: T;
        badges?:
          | T
          | {
              icon?: T;
              label?: T;
              id?: T;
            };
        submitLabel?: T;
        successMessage?: T;
      };
  contactMethods?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        description?: T;
        badges?:
          | T
          | {
              icon?: T;
              label?: T;
              id?: T;
            };
      };
  studioLocation?:
    | T
    | {
        eyebrow?: T;
        headlineLine1?: T;
        headlineLine2?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule-a-call-page_select".
 */
export interface ScheduleACallPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        titleLine1?: T;
        titleLine2?: T;
        subtitle?: T;
      };
  calendar?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        sessionLabel?: T;
        durationLabel?: T;
        monthLabel?: T;
        selectDateLabel?: T;
        selectTimeLabel?: T;
        confirmLabel?: T;
        confirmedLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}